version: '3.8'

services:
  cart-service:
    build: .
    container_name: cart-service
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-cart:5432/cart_db
      - PRODUCT_SERVICE_URL=http://product-service:8001
      - JWT_SECRET_KEY=zAP5LmC8N7e3Yq9x2Rv4TsX1Wp7Bj5Ke
    depends_on:
      - postgres-cart

  postgres-cart:
    image: postgres:15
    container_name: postgres-cart
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cart_db
    volumes:
      - postgres-cart-data:/var/lib/postgresql/data

volumes:
  postgres-cart-data: 