"""add unique index for cart_items (cart_id, product_id)

Revision ID: 605fa30c44a7
Revises: 
Create Date: 2025-04-16 09:07:47.132710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605fa30c44a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cart_items_cart_id_product_id_key', 'cart_items', ['cart_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_cart_id_product_id_key', 'cart_items', type_='unique')
    # ### end Alembic commands ###
