"""Change cascade behavior in models

Revision ID: 27664ed41dc6
Revises: faab783cf97b
Create Date: 2025-03-14 19:09:05.904074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27664ed41dc6'
down_revision: Union[str, None] = 'faab783cf97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('products_subcategory_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_brand_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_country_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'countries', ['country_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_country_id_fkey', 'products', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_brand_id_fkey', 'products', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_subcategory_id_fkey', 'products', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
