version: '3.8'

services:
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: cosmetic_store/celery_service:latest
    command: celery -A celery_app worker --loglevel=info --concurrency=4
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - app_network
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: cosmetic_store/celery_service:latest
    command: celery -A celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
    volumes:
      - .:/app
    networks:
      - app_network
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: cosmetic_store/celery_service:latest
    command: celery -A celery_app flower --port=5555 --loglevel=info
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    volumes:
      - .:/app
    networks:
      - app_network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  app_network:
    external: true 